typedef Window WindowProxy;


// currently unknown types that need to be handled somehow
interface MediaStream { };
interface OverconstrainedError { };
typedef DOMString CSSOMString;
interface Uint8ClampedArray { };

interface ByteString { };

interface ReadableStream { };
